# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /media/ad/Area51/workspace/assignments/col216/assignments/arm_processor/lab4_vivado/lab4_vivado.cache/wt [current_project]
set_property parent.project_path /media/ad/Area51/workspace/assignments/col216/assignments/arm_processor/lab4_vivado/lab4_vivado.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /media/ad/Area51/workspace/assignments/col216/assignments/arm_processor/lab4_vivado/lab4_vivado.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /media/ad/Area51/workspace/assignments/col216/assignments/arm_processor/shifter.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top shifter -part xc7a35tcpg236-1


write_checkpoint -force -noxdef shifter.dcp

catch { report_utilization -file shifter_utilization_synth.rpt -pb shifter_utilization_synth.pb }
